enterprise_ecommerce_elt:
  target: cloud_warehouse
  outputs:
    cloud_warehouse:
      type: postgres
      host: postgres
      user: admin
      password: SecurePass123!
      port: 5432
      dbname: ecommerce_warehouse
      schema: public
      threads: 4
      keepalives_idle: 0
      search_path: [public, raw, staging, analytics]
      
